### ISSUE TITLE
Weekly view in calendars is not working since notion database update in March

### ISSUE THREAD

**Issue by forrest-herman** [notion-enhancer/notion-repackaged#100]
**What is happening?**
Weekly view in calendars is not working. Shows the whole month.

**What should be happening?**
Calendar databases named `weekly` should show only the current week.

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/58410716/172692824-3c0cd3d0-c7d9-45ee-bf8b-37f9ea1e1f14.png)

**Operating system/browser name & version:**
Windows 10 and MacOS

**notion-enhancer and/or notion-repackaged version:**
Latest notion-repackaged—notion-enhancer v0.11.0-dev

**notion-enhancer configuration (enabled/disabled mods and their settings):**
no other mods.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/751
