### ISSUE TITLE
Portable version of  Notion-Enhanced does not work correctly

### ISSUE THREAD

**Issue by imyu37** [notion-enhancer/notion-repackaged#101]
Portable version unzipped from Notion-Enhanced-2.0.18-1-win.zip does not work correctly. There is no setting tab of notion-enhanced in the original notion as the following pic. shown. I deleted all files about Notion-enhanced on my pc including which are in user's directory. The new Notion enhanced unzipped doesnot work correctly as same as before.

![图片](https://user-images.githubusercontent.com/4496251/173983846-57995508-742d-405e-b948-91c8b080961e.png)

**Operating system/browser name & version:**
OS:	Windows 10 professional
version: 21H1 19043.1620

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762
