### ISSUE TITLE
The notion-enhancer option has gone

### ISSUE THREAD

**Issue by hamidreza4dev** [notion-enhancer/notion-repackaged#102]
**What is happening?**
The notion-enhancer option seems to have gone.
so how can I enter the notion-enhancer page?

**What should be happening?**
It was previously under the setting and members option

**Screenshots:**
![image](https://user-images.githubusercontent.com/69403093/174634354-918750f7-304f-4c4d-9126-6bea331aacd6.png)

**Operating system/browser name & version:**
OS: arch linux Linux x64
DE: Plasma 5.24.3

**notion-enhancer and/or notion-repackaged version:**
2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
instalation is fresh.

**Comment by EternalDusk** [comment]
Just had this problem. It's something to do with the new UI changes that were silently pushed.

To open the notion enhancer window, press the default keybind Control+Alt+E

**Comment by itaiperi** [comment]
Also happened to me, I'm on a Mac M1 (late 2021), MacOS version 12.3.1

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762
