### ISSUE TITLE
Nothing changed for macos catalina 10.15.7

### ISSUE THREAD

**Issue by Tonny-zhou** [notion-enhancer/notion-repackaged#103]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
I have downloaded the notion-enhanced binary executable file from the link (https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-2.0.18-1.dmg) and removed it to the /Applications. However, when i opened this program, i could not find the notion-enhancer in anywhere, i.e., everything in the notion-enhanced program is the same as it in the normal notion program.

**What should be happening?**

**Screenshots (if applicable):**

**Operating system/browser name & version:**
macos catalina 10.15.7
**notion-enhancer and/or notion-repackaged version:**
v0.11.0
**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762
