### ISSUE TITLE
Notion Enhancer Menu Not Showing

### ISSUE THREAD

**Issue by Kalako** [notion-enhancer/notion-repackaged#105]
Hello. I recently downloaded the notion enhancer REPACKAGED, and deleted the .notion-enhancer file. I opened the application, but no menu to be seen. I also tried the key shortcut "Ctrl + Alt + E", which didnt do anything. I also cant find the icon in the icon tray. When downloading earlier versions, I get the icon in the icon tray, but then the notion enhancer automatically gets updated to the latest version.

When opening the console, this is what I get:
![image](https://user-images.githubusercontent.com/79514552/182914523-d876e17d-9c99-4133-b66f-05353936a953.png)

My operating system is windows 10 by the way.

**Comment by shiraari** [comment]
Did you try to show Enhancer Menu by typing in "Console" tab `__enhancerElectronApi.focusMenu()`? About tray, you need to install/enable it from that menu like this:
![image](https://user-images.githubusercontent.com/69073674/182916387-2d493f5f-2007-454d-aedc-993674d8ddf9.png)

**Comment by Kalako** [comment]
Yes I did. This is what happened: ![unknown-28.png](https://user-images.githubusercontent.com/79514552/182928475-cbaef5a7-8a7e-454e-b609-39ccd643e5e8.png)

**Comment by shiraari** [comment]
Something seems wrong (read error) that you have .notion-enhancer (as a folder), could you try to remove it and rerun notion-enhancer?

**Comment by Kalako** [comment]
The thing is I have already done that

**Comment by Kalako** [comment]
Okay so I had deleted the file but there was a folder which I deleted called ".notion-enhancer", like you said. But now whenever I start notion enhanced (repackaged), it automatically creates a new .notion-enhancer file each time I start it.

**Comment by dragonwocky** [comment]
@Kalako it uses the file to store settings, that's expected behaviour. you only need to delete `.notion-enhancer` if it's a **folder**.

this sounds like it's resolved?
