### ISSUE TITLE
No notion-enhancer menu item available after installing on linux pop-os (22.04)

### ISSUE THREAD

**Issue by bartmoc** [notion-enhancer/notion-repackaged#109]
After I installed notion-app-enhanced via:
```
➜  ~ sudo dpkg -i ~/Downloads/notion-app-enhanced_2.0.18-1_amd64.deb

```
I have no "enhancer option".
According to the doc, there should be the option:
https://notion-enhancer.github.io/getting-started/basic-usage/
"the only noticeable difference should be an extra option in the Notion sidebar labelled  notion-enhancer."

```
➜  ~ uname -a
Linux pop-os 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux
```

Here is my view:
![image](https://user-images.githubusercontent.com/16946872/185850505-e970f64b-f053-4132-bed8-af0db58879e5.png)

**Comment by bartmoc** [comment]
I expect notion-enhancer menu item as below: 
![image](https://user-images.githubusercontent.com/16946872/185850864-54d0fc3d-4720-4d9d-965f-dbbddae951a2.png)

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/762

**Comment by bartmoc** [comment]
Thx @dragonwocky for the blazing fast response. All good. Thx :)
