### ISSUE TITLE
Notion enhancer network error

### ISSUE THREAD

**Issue by amiria703** [notion-enhancer/notion-repackaged#113]
**What is happening?**
Instead of loading notion I get network error.
It tries to access the address `notion://www.notion.so` and it fails.

**What should be happening?**
As usual notion should loads.

**Screenshots (if applicable):**
![image](https://github.com/notion-enhancer/notion-repackaged/assets/54179379/a639eca1-bd9a-43b7-b4e2-8f0afeb9c9df)

**Operating system/browser name & version:**
Arch Linux

**notion-enhancer and/or notion-repackaged version:**
I use choatic-aur version built from this AUR package: https://aur.archlinux.org/packages/notion-app-enhanced
chaotic-aur/notion-app-enhanced 2.0.18-1.4

**notion-enhancer configuration (enabled/disabled mods and their settings):**
I don't know what to fill here as I couldn't use notion-enchancer.

**Comment by dragonwocky** [comment]
@amiria703 does the Notion website work for you? How about the normal/vanilla Notion app?

I'm not seeing this when I use notion-app-enhanced, so my initial reaction is that it more likely is actually a network error and isn't a notion-enhancer bug.

**Comment by amiria703** [comment]
> Does the Notion website work for you?

Yes.
@dragonwocky 

> How about the normal/vanilla Notion app?

It works.

**Comment by amiria703** [comment]
It seems so weird but just by reinstalling notion-app-enhanced problem solved.
