### ISSUE TITLE
When I start notion-enhancer, infinite loading error

### ISSUE THREAD

**Issue by tkdemd1234** [notion-enhancer/notion-repackaged#118]
**What is happening?**
infinite loading happen occured
**What should be happening?**
Solve infinite loading problems
**Screenshots (if applicable):**
![20231030_131729](https://github.com/notion-enhancer/notion-repackaged/assets/48245903/699d6834-8aca-41f2-bb13-be2d73a53ce9)
![20231030_131825](https://github.com/notion-enhancer/notion-repackaged/assets/48245903/210afdce-19cf-49a1-a0bb-2f36a707b70b)

**Operating system/browser name & version:**
Window 10, Chrome 118.0.5993.118 / Notion-Enhanced-Setup-2.0.18-1
**notion-enhancer and/or notion-repackaged version:**
notion-enhancer
**notion-enhancer configuration (enabled/disabled mods and their settings):**

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/116

**Comment by Mirissa-Youth** [comment]
When  starting notion-enhancer（the lastest version on window）, it will appear infinite loading error，what should i do

**Comment by dragonwocky** [comment]
@GRACEBL you should see https://github.com/notion-enhancer/notion-repackaged/issues/116
