### ISSUE TITLE
Notion doesn't open, it just keeps loading

### ISSUE THREAD

**Issue by dieggpereira** [notion-enhancer/notion-repackaged#119]
For a few days now my notion desktop is no longer starting, it just keeps loading forever (print 1). I tried reinstalling several times and even followed the steps for editing `preload.js` in `app.asar` (which once worked for me when I had problems with "." and "/", but now it doesn't work (print 2)).
Does anyone have any idea what could be happening?

**Print 1**
![Capture d’écran du 2023-11-03 22-14-07](https://github.com/notion-enhancer/notion-repackaged/assets/80273980/1f5c691e-2b32-45fa-8e4f-670fe2358cd4)

**Print 2**
![Capture d’écran du 2023-11-03 22-13-22](https://github.com/notion-enhancer/notion-repackaged/assets/80273980/69bdb3fa-f8b6-4fcf-9070-6679b7425e05)

**Comment by dragonwocky** [comment]
see #116, there's a second bit of code to add to `preload.js` now

**Comment by dieggpereira** [comment]
Thank you so much (and sorry). My mistake was exactly inserting the old script.
