### ISSUE TITLE
App keeps loading forever

### ISSUE THREAD

**Issue by 0xAnan** [notion-enhancer/notion-repackaged#121]
The application keeps loading forever and doesn't open
Windows11 and I'm using the app not the browser
![Screenshot (67)](https://github.com/notion-enhancer/notion-repackaged/assets/130401572/d855e2fe-b2db-430f-8834-c0d67ac998fb)

**Comment by hlvt** [comment]
Same.

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/116
