### ISSUE TITLE
Refused to load style sheet

### ISSUE THREAD

**Issue by MahmoudKhalefa2020** [notion-enhancer/notion-repackaged#130]
I installed Notion Enhancer and I open Notion browser and when redirect to Notion Enhancer app I open console app and see this errors 
![image](https://github.com/notion-enhancer/notion-repackaged/assets/82944257/7932e63c-f604-4152-94ae-13b97b640324)
and it's cause infinite loop 
![image](https://github.com/notion-enhancer/notion-repackaged/assets/82944257/d80462cc-4204-42ad-8c62-16961ee9f07f)

**Comment by dragonwocky** [comment]
As I noted in #129, the issue of infinite loading has been reported in #116. There is also [a solution](https://github.com/notion-enhancer/notion-repackaged/issues/116#issuecomment-1796504247) there that you can follow to get around the infinite loading on your own computer.
