### ISSUE TITLE
Enhanced options not working

### ISSUE THREAD

**Issue by leonardopivete** [notion-enhancer/notion-repackaged#14]
![Captura de tela 2021-07-16 041657](https://user-images.githubusercontent.com/85177540/125908097-390fe100-1413-4a2c-8157-6e5073caced5.png)

in the left is the notion app (2.0.11), in the right is the enhanced (2.0.16), and in the middle is the enhanced mini window options. as you can see the enhanced options is not applying to the notion itself, nor the vanilla or the enhanced versions, but the options i choose, like the theme etc. are applying to the mini enhanced window, so idk, its kind working? i have no ideia to what to do, but i really want to test the enhanced version

i really suck at coding, so if there any line/row that i put there to give any info, pls tell me. i use the windows version

**Comment by jamezrin** [comment]
Did you check if it works now? This is an issue of notion-enhancer itself, and eventually fixes itself by restarting the app. It will be fixed soon.

**Comment by zerorabb** [comment]
Even upon restarting several times, it's not fixing itself. Nothing works at the moment.
Can confirm it's a Notion Enhancer problem, I have the same issue with the normal Notion with that installed - even restarting does nothing.

**Comment by sereksim** [comment]
If it's a problem of notion-enhancer, I would suggest creating an issue at [notion-enhancer](https://github.com/notion-enhancer/notion-enhancer) @leonardopivete @zerorabb

**Comment by zerorabb** [comment]
Actually, I managed to get Notion Enhancer working when applied to vanilla Notion (I tried installing Notion Enhancer when Notion was still open)
However, Notion Repackaged still won't work.

**Comment by jamezrin** [comment]
Please, try the new version 2.0.16-2 which should fix this (and other issues)

https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-2
