### ISSUE TITLE
Themes not working on Windows

### ISSUE THREAD

**Issue by pomt98** [notion-enhancer/notion-repackaged#17]
I read various people have had similar issues on Linux and MacOS and it corrects itself after a few restarts so have tried doing that (50+ restarts, clearing the entire task in the memory, restarting the system and then trying to see if it works) but it hasn't YET worked for me, so just wanted to put it up here incase someone has a solution for Windows.

![Screenshot 2021-08-04 142550](https://user-images.githubusercontent.com/35378104/128153650-940b5e18-4ce5-44c1-916e-a585e0dd5905.png)

:)

**Comment by elbyte** [comment]
no solution as yet! but also had this issue (again after re-installing due to another issue). But interestingly I reinstalled on two Windows 10 computers (my desktop and laptop), and it only fixed itself after a couple restarts on my laptop and not on my desktop.

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/291
