### ISSUE TITLE
Default to dark theme

### ISSUE THREAD

**Issue by RealTheSunCat** [notion-enhancer/notion-repackaged#19]
Hi! I've been a huge fan of Notion Enhanced and its features, and I really appreciate the work you're putting into this.

One thing I would really appreciate was an enhancement to set a default theme other than white. Every time I open Notion, I have to press the keyboard shortcut to switch to dark theme because the notes I take are designed with the dark background and white text in mind.
Would it be possible to set the dark theme as default through Notion Enhanced?
Thanks.

**Comment by dragonwocky** [comment]
go into your notion settings (actual notion settings, not enhancer settings) and under appearance set it to 'dark'
