### ISSUE TITLE
Permission problem on Notion Enhanced for Mac

### ISSUE THREAD

**Issue by salutmathilde** [notion-enhancer/notion-repackaged#20]
Hi ! I tried to fix my problem, but already I don't find any solution so, I need your help :(
I have an error message when I try to open my Notion Enhance Application 
![image](https://user-images.githubusercontent.com/64541635/129216658-e2393477-3dba-4b3d-8532-76be7bd2b637.png)
Notion is ok, but this one doesn't work.
I have this message
![image](https://user-images.githubusercontent.com/64541635/129216833-691d53de-1361-4dc9-a400-25f692f0ea6c.png)
In english : "You do not have the permissions to open the "Notion Enhanced" application. Contact your network or computer administrator for assistance."

Anyone can help me ?

Thank a lot !

**Comment by jamezrin** [comment]
I'm sorry, I don't have a Mac, so I don't know why would this happen. Is your user allowed to run unsigned apps? Maybe there is a user policy setting that doesn't allow you to do this.

Also, even if your user has permissions to do that, you'll get a warning for opening an unsigned app, for that check this issue:
https://github.com/notion-enhancer/notion-repackaged/issues/4
