### ISSUE TITLE
!! The maximize, minimize and close buttons are glitching out D:

### ISSUE THREAD

**Issue by drunkzurg** [notion-enhancer/notion-repackaged#21]
![image](https://user-images.githubusercontent.com/89298319/130317817-db15316c-bea0-41d7-ace8-53d214cc5445.png)

**Comment by jackoregankenny** [comment]
Same issue on the pre-packaged windows across 2 versions.

**Comment by jamezrin** [comment]
Please, try the new version 2.0.16-2 which should fix this (and other issues)

https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-2

**Comment by metalzero24** [comment]
Having this issue with the latest 2.0.16-2, sorry for the duplicate just saw this issue.

**Comment by ayush729p** [comment]
Yeah same bug in my case too.

**Comment by dragonwocky** [comment]
the primary issue for this bug is https://github.com/notion-enhancer/notion-enhancer/issues/291
