### ISSUE TITLE
Apple M1: I do not have permission to open Notion Enhanced 

### ISSUE THREAD

**Issue by rahulpatel1936** [notion-enhancer/notion-repackaged#22]
<img width="252" alt="Screen Shot 2021-08-21 at 3 34 09 PM" src="https://user-images.githubusercontent.com/85363816/130333139-3f478803-147d-4067-9718-b111338c0c36.png">

Hello, I have a MacBook Pro (M1) and downloaded the following file: Notion-Enhanced-2.0.16-1-mac.zip. However, upon opening it, I found out that I don't have permission (see screenshot) to access the application. I was wondering what the next steps are?

**Comment by jamezrin** [comment]
Please, check https://support.apple.com/en-au/guide/mac-help/mh40616/mac

**Comment by sageraymac** [comment]
@jamezrin i had this problem but was able to do the simple .dmg version totally hassle free. try downloading that one instead

**Comment by sageraymac** [comment]
although now i have a whole new set of issues w/ certain extensions not working but at least I have the app running
