### ISSUE TITLE
Minimize, Maximize and Close Buttons Glitched Out

### ISSUE THREAD

**Issue by metalzero24** [notion-enhancer/notion-repackaged#23]
![image](https://user-images.githubusercontent.com/49725809/131245605-64446719-6380-44a7-9638-5803257890fd.png)

Latest version on Windows 11 looks like this, tried disabling scaling, didn't work. (Official app looks normal)

**Comment by dragonwocky** [comment]
the primary issue for this bug is https://github.com/notion-enhancer/notion-enhancer/issues/291
