### ISSUE TITLE
Window controls display incorrectly on hidden title bar in Windows 11 

### ISSUE THREAD

**Issue by scratchfive** [notion-enhancer/notion-repackaged#24]
On Windows 11 (21H2 build 22000.168) running Notion-repackaged 2.0.16 (rev 2) results in the window control buttons becoming oversized and bleeding into the app itself. This only seems to happen for me when the title bar is set to hidden.

[Screenshot](https://imgur.com/mWPQzKa)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/291
