### ISSUE TITLE
Minimize/Maximize/Close Buttons Glitching

### ISSUE THREAD

**Issue by starryyskies** [notion-enhancer/notion-repackaged#25]
I am on Windows, and I am using the repackaged version through the exe file. For some reason, the buttons in the top right corner are glitching for me. They are usually all lined up next to each other. They're not supposed to be underneath one another like shown in the photo...
![Screenshot 2021-09-03 123251](https://user-images.githubusercontent.com/89066472/132051703-92b80d07-0f3c-4001-bc36-c3f574a010c1.jpg)
Also, like 90% of the time, if I hover my mouse over the Close button, they disappear.
Not sure what to do. I'm not familiar with coding, so I have no idea where to go to fix it.

**Comment by Rereyuop** [comment]
![image](https://user-images.githubusercontent.com/56964252/132082897-a5055ac5-d040-4901-91e9-0925a0805131.png)
On the latest dev version of windows 11 (22449) they be like this.

**Comment by dragonwocky** [comment]
#291

**Comment by Rereyuop** [comment]
> @Rereyuop see [notion-enhancer/notion-enhancer#291](https://github.com/notion-enhancer/notion-enhancer/issues/291), these are different bugs.

thanks, this app is brilliant!

**Comment by dragonwocky** [comment]
@starryyskies see https://github.com/notion-enhancer/notion-enhancer/issues/572
