### ISSUE TITLE
Enhancer not working porperly

### ISSUE THREAD

**Issue by Blacksuan19** [notion-enhancer/notion-repackaged#3]
i just installed this package from the AUR.
the enhancer does not work properly, most of the extensions are ignored. the only extension that partially works is the panel icons, even that is messed up, i launched the binary from terminal and this is the error it shows.

**Log:**
```
00:28:15.875 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}

```

**System:**
Arch Linux with Plasma + BSPWM

 
**Screenshots:**
the theme is not applied to notion itself and panel icons are messed up, also no go to top button and help is still there despite being hidden from enhancer settings.1
![image](https://user-images.githubusercontent.com/10248473/124500252-01fb4280-ddf2-11eb-9a25-d8d3559c506d.png)

**List of enabled Mods:**
```
{
  "conflicts": { "dark": false, "light": false },
  "e0700ce3-a9ae-45f5-92e5-610ded0e348d": { "enabled": true },
  "752933b5-1258-44e3-b49a-61b4885f8bda": { "enabled": true },
  "0a958f5a-17c5-48b5-8713-16190cae1959": { "enabled": true },
  "69e7ccb2-4aef-484c-876d-3de1b433d2b9": { "enabled": true },
  "548fe2d7-174a-44dd-88d8-35c7f9a093a7": { "enabled": true },
  "d61dc8a7-b195-465b-935f-53eea9efe74e": { "enabled": true }
}
```

**Comment by jamezrin** [comment]
Hey, did you use notion-app-enhanced before? Did you have this issue back then?

**Comment by Blacksuan19** [comment]
yes i did have the same issue but i didn't have time to diagnose it so i went back to notion-app 2.0.11 when the enhancer worked fine and used that until now

**Comment by jamezrin** [comment]
Errors with missing/weird icons eventually start working by themselves. It's weird but it eventually goes away.

The same happens with the theme, it won't work until it does, and then it will work every time.

Right now it's hard to hotfix these errors, it's not a fault of notion-repackaged per se, it's more of an incompatibility between notion-enhancer and notion 2.0.16.

The missing `focused_window.isMaximized` function error is certainly fixable, I think it's because you are using a WM. I'll try to fix this one with a patch, it might in turn fix the other issues you are facing.

**Comment by Blacksuan19** [comment]
Okay, i will be waiting for the patch.

**Comment by Blacksuan19** [comment]
**Update:** mods started randomly working today, that error is still there and seems harmless.
