### ISSUE TITLE
Side panel not collapseable

### ISSUE THREAD

**Issue by jamboluco** [notion-enhancer/notion-repackaged#32]
I've got the side panel turned on and outliner but it won't collapse as per https://github.com/notion-enhancer/notion-enhancer/pull/284

**Comment by albertopasqualetto** [comment]
Also for me not collapsible

**Comment by AndyPro720** [comment]
It isn't collapsible and doesn't show the headings as well.

**Comment by HaiyiMei** [comment]
Me too

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/578 and https://github.com/notion-enhancer/notion-enhancer/issues/596
