### ISSUE TITLE
App Window Showing up with Cmd+Shift+A

### ISSUE THREAD

**Issue by rafarc21** [notion-enhancer/notion-repackaged#35]
Hi,

Whenever I press Cmd+Shift+A on my Mac, the Notion Enhanced app window shows up/hides. 

I couldn't find where to change this shortcut and it's not a mac specific. It's also conflicting with another system-wide shortcut I have. Do you have any device on how to change this?

**Comment by dragonwocky** [comment]
you can change it in the enhancer menu, the "window display hotkey" option under the core
