### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by 108anup** [notion-enhancer/notion-repackaged#37]
I can only see the loading ring animation on launching Notion.

In the console log, I see error messages saying:

```
WebSocket connection to 'ws://localhost:37477/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by 108anup** [comment]
Same error occurs with both enhanced and vanilla versions.

**Comment by dragonwocky** [comment]
This is known to occur if you have multiple instances of Notion running at the same time. Make sure you aren't running both vanilla and enhanced Notion.

**Comment by 108anup** [comment]
I am using Ubuntu 18.04.

I removed all notion packages using: `apt-get remove notion*`, `rm -fr ~/.config/notion*`. And kept only the vanilla notion. Rebooted, still same issue.

**Comment by 108anup** [comment]
I had previously installed notion on wine and the notion-linux package but have removed them as well.

**Comment by 108anup** [comment]
Please let me know what other things I could try or what more information I could provide.

**Comment by dragonwocky** [comment]
could this be https://github.com/notion-enhancer/notion-repackaged/issues/27?

**Comment by sathoril** [comment]
I've just downloaded the package and it shows me the same error:

![image](https://user-images.githubusercontent.com/29286540/139594223-537f8941-6b90-4fc9-afd4-2cc664c08a4f.png)

Already reinstalled and killed all related processes but nothing seems to work.

**Comment by tinkicker** [comment]
Just commenting to add that this has happened to me just as with 108anup (both versions). I'm not as knowledgeable in diagnosing this as you all seem to be, so I don't have log data for you, but the effect is the same and I just basically wanted to emphasize that this doesn't appear to be an isolated thing.

MX Linux 21.x here on an OLD converted Acer Chromebook.

**Comment by lemont037** [comment]
Same problem on Deepin, Debian based, on fresh install.
![Capturar_notion-app_20211121214558](https://user-images.githubusercontent.com/32838521/142786178-3b1d94e5-1e28-4cb8-85c4-f5a1b4ecaf95.png)
.

**Comment by tinkicker** [comment]
Just did a new install on MX Linux 21 XFCE and the app took a very long time to get past the blank white screen but it finally did. I logged in and it's working now.

**Comment by dragonwocky** [comment]
if you scroll to the top of the console errors, does it show anything other than just the ws:// error? e.g. an SqliteSchemaMismatch?

**Comment by isteqra** [comment]
same problem from mx19.4 
[problem_image](https://suar.me/Gxp2d)
and that log file form ~.config/notion-app/logs/
`[2021-12-07 16:14:30.926] [info] Checking for update
[2021-12-07 16:14:31.386] [info] Error reading /home/Ismail/.config/notion-app/cookies.json {
  constructor: 'Error',
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/Ismail/.config/notion-app/cookies.json',
  stack: "Error: /home/Ismail/.config/notion-app/cookies.json: ENOENT: no such file or directory, open '/home/Ismail/.config/notion-app/cookies.json'\n" +
    '    at Object.openSync (fs.js:466:3)\n' +
    '    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)\n' +
    '    at Object.readFileSync (fs.js:368:35)\n' +
    '    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8592)\n' +
    '    at Object.readFileSync (/opt/Notion/resources/app.asar/node_modules/jsonfile/index.js:61:22)\n' +
    '    at JsonStore.loadSync (/opt/Notion/resources/app.asar/main/JsonStore.js:37:44)\n' +
    '    at new JsonStore (/opt/Notion/resources/app.asar/main/JsonStore.js:14:14)\n' +
    '    at Object.<anonymous> (/opt/Notion/resources/app.asar/main/schemeHandler.js:24:25)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1152:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)'
}
[2021-12-07 16:14:34.186] [info] {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/Ismail/.config/notion-app/notionAssetCache-v2/latestVersion.json'
  }
}
[2021-12-07 16:14:34.220] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Notion/resources/app-update.yml'
[2021-12-07 16:14:34.222] [info] {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/Ismail/.config/notion-app/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/Ismail/.config/notion-app/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/Ismail/.config/notion-app/notionAssetCache-v2/latestVersion.json'
  }
}
[2021-12-07 16:14:34.223] [info] {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}
[2021-12-07 16:14:34.223] [info] {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
[2021-12-07 16:14:34.224] [info] {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}`

**Comment by leonardoholberg** [comment]
I'm getting the same problem with ARM version on M1 Mac. The x64 version works fine, but I of course slow.
<img width="1439" alt="Screenshot 2021-12-07 at 16 56 27" src="https://user-images.githubusercontent.com/25032695/145063741-d694a053-5e26-4569-88b5-578cb2e6a81f.png">

**Comment by dragonwocky** [comment]
@leonardoholberg yeah, that's just cos ARM is broken and there's not much we can do about that in the foreseeable future, sorry: https://github.com/notion-enhancer/notion-repackaged/issues/9
