### ISSUE TITLE
.zip version for mac not able to open

### ISSUE THREAD

**Issue by sageraymac** [notion-enhancer/notion-repackaged#42]
Generated these details on the error: 

Process:               Notion Enhanced [21822]
Path:                  /private/var/folders/*/Notion Enhanced.app/Contents/MacOS/Notion Enhanced
Identifier:            com.github.notion-repackaged
Version:               2.0.16-5 (2.0.16-5)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Notion Enhanced [21822]
User ID:               501

Date/Time:             2021-09-28 00:28:47.970 -0700
OS Version:            macOS 11.5.1 (20G80)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        F287C13F-0D3F-779B-EE8D-8E9CCF8714F4

Sleep/Wake UUID:       476D5E63-3659-4C4E-AB17-54A31CAC5EF6

Time Awake Since Boot: 420000 seconds
Time Since Wake:       1000 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: B936FA17-1090-3677-8A1A-0FB7DE3CEC6C
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/Notion Enhanced.app/Contents/MacOS/Notion Enhanced
  Reason: no suitable image found.  Did find:
	/private/var/folders/qw/y5kjwlc52t95pqvpkx1q7k8h0000gn/T/AppTranslocation/53C1D01C-AD61-4C48-8E84-B3814BA7AA32/d/Notion Enhanced.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/private/var/folders/qw/y5kjwlc52t95pqvpkx1q7k8h0000gn/T/AppTranslocation/53C1D01C-AD61-4C48-8E84-B3814BA7AA32/d/Notion Enhanced.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x1049fd000 -        0x104a24fff +com.github.notion-repackaged (2.0.16-5 - 2.0.16-5) <78B92786-16F2-3C2B-86DC-F633B22A7F09> /var/folders/*/Notion Enhanced.app/Contents/MacOS/Notion Enhanced
       0x112edd000 -        0x112f78fff  dyld (852.2) <57DB2053-BFD5-3683-97C6-F1DB2A1F1D09> /usr/lib/dyld

Model: MacBookPro14,3, BootROM 429.140.8.0.0, 4 processors, Quad-Core Intel Core i7, 2.8 GHz, 16 GB, SMC 2.45f5
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555Item, Radeon Pro 555, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1680.8)
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.4

**Comment by jamezrin** [comment]
How did you extract the zip file? I can't test this myself as I don't have a Mac machine, but the zip builds should work just like the DMG file if every file inside the zip is extracted and with the correct permissions.

**Comment by sageraymac** [comment]
> How did you extract the zip file? I can't test this myself as I don't have a Mac machine, but the zip builds should work just like the DMG file if every file inside the zip is extracted and with the correct permissions.

i just opened it w/ mac’s native .zip opener. opening the app itself i had to do all these terminal commands for permission since it’s not signed off by a developer and then even after being able to attempt to open it the above error message was given and i was notified that i can’t even open it because of that error.
