### ISSUE TITLE
Trojan Detected Alert!

### ISSUE THREAD

**Issue by mohamed-okasha** [notion-enhancer/notion-repackaged#43]
Is this alert normal with the re-packaged windows version?
![image](https://user-images.githubusercontent.com/6838651/135490910-05fc9bc4-cae7-4587-9c9f-e57291b926f5.png)

**Comment by jamezrin** [comment]
Yes, the app is not signed and might cause Windows or AVs to not trust it. The app is built openly and only includes trusted code, so you can safely whitelist it.
