### ISSUE TITLE
When clicking the icon on Dock it opens a second window

### ISSUE THREAD

**Issue by Valeria** [notion-enhancer/notion-repackaged#47]
Running the repackaged .dmg on Intel MacOS Big Sur 11.6

When the app is opened and I click it's icon on the dock (to regain focus coming from another app) it loads a second Notion window. If I close one of the two windows and click the dock icon again the same thing happens.

Curiously, when two windows are open it stops spawning new windows (always 2, never 3 or more).

Only using the default enhancements and a theme (Neutral theme)

**Comment by qeude** [comment]
I've noticed the same problem 👍🏼
