### ISSUE TITLE
Virus detected by Kaspersky

### ISSUE THREAD

**Issue by YunhaoJiang** [notion-enhancer/notion-repackaged#48]
Trying to run the setup program of [this vesion](https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5), and the Kaspersky on my computer won't allow it to start up, showing a virus detected.
Virus type: UDS:Trojan.Win32.Diztakun

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/notion-repackaged/issues/43
the app is unsigned, so pops up a warning, but there is no virus and the entire build process is publicly available for review
