### ISSUE TITLE
[deb] libappindicator is deprecated, please switch to AyatanaIndicator

### ISSUE THREAD

**Issue by MicroJoe** [notion-enhancer/notion-repackaged#51]
libappindicator1 is deprecated ([details here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037)), and should be replaced with [libayatana-appindicator3](https://tracker.debian.org/pkg/libayatana-appindicator).

The former is [unavailable in Debian Bullseye](https://tracker.debian.org/pkg/libappindicator) (as well as unstable), and makes installation impossible:

```console
$ LANG=en_EN.utf-8 sudo apt install notion-app-enhanced
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 notion-app-enhanced : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

This bug is probably coming from Electron, so it should be linked to the corresponding upstream issue.

See how this was handled in Signal-Desktop: https://github.com/signalapp/Signal-Desktop/issues/4761

**Comment by muammar** [comment]
Is there any update? This package is not installable on Debian.

**Comment by jamezrin** [comment]
A new version containing this and other fixes will be released very soon, just wait a little bit longer.
