### ISSUE TITLE
Can't install with package manager

### ISSUE THREAD

**Issue by cstby** [notion-enhancer/notion-repackaged#55]
After using the instructions in the readme to add your repository, I get the following error when I run `sudo apt install notion-app-enhanced`:
`Repository is broken: https://apt.fury.io/notion-repackaged  notion-app-enhanced 2.0.16-5 has no Size information`.

**Comment by function2-llx** [comment]
Same here, I'm on ubuntu 21.10

**Comment by Arjun31415** [comment]
Yes same issue 
Apart from that i also get unable to connect to in.archive.ubuntu.com:80 and connection timed out

**Comment by dragonwocky** [comment]
@Arjun31415 that sounds like a network problem, different to the one reported here.

**Comment by Arjun31415** [comment]
> @Arjun31415 that sounds like a network problem, different to the one reported here.

Sorry mb 
I now get this -
```
sudo apt install notion-app-enhanced
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package notion-app-enhanced
```

**Comment by dragonwocky** [comment]
@Arjun31415 hmm, I see. we'll look into this - for now just download and install the .deb from https://github.com/notion-enhancer/notion-repackaged/releases/tag/v2.0.16-5

**Comment by jamezrin** [comment]
I cannot reproduce on Ubuntu 20.04 LTS, does this only happen on 21.04?

**Comment by jamezrin** [comment]
Fixed, was an issue on Gemfury's side. 

`Thanks for the reporting this. "Size" is a standard field in the Gemfury APT repos, but I'm not sure why, the specific file had a blank "Size" field. I've rebuilt your index, and the "Size" field is now correct. This was a a race condition with indexing newly-uploaded files. We are fixing the bug now.
`
