### ISSUE TITLE
Themes don't work on table headers.

### ISSUE THREAD

**Issue by shahiljain** [notion-enhancer/notion-repackaged#59]
OS: Pop_OS! 21.04 (Ubuntu Based)
![image](https://user-images.githubusercontent.com/75173792/142571617-314d781d-47ac-4b13-97ab-dc16ee23fe27.png)
![image](https://user-images.githubusercontent.com/75173792/142571784-06dd0f71-7ecd-4083-a9b0-eede04837677.png)

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/649
