### ISSUE TITLE
Excessive Power Consumption when Running Notion

### ISSUE THREAD

**Issue by Siddapa** [notion-enhancer/notion-repackaged#61]
I've been using Notion for a couple days now and my battery life has significantly dropped when running it. I even checked it using powertop and found wattage for just notion to be almost 15 W. Anyone know why this is happening? I'm currently running Pop OS and installed it via apt

![NotionPowerUsage](https://user-images.githubusercontent.com/44073565/143901134-983d20aa-caab-4d14-baf3-3871ee516ec4.png)
t.

**Comment by lihuelworks** [comment]
Happened to me too on Windows, to the point it crashed other Chrome windows. Didn't happen with vanilla, is there any way I can throw a log with more info? (or any info that could be useful in that matter)

**Comment by dragonwocky** [comment]
it's a combination of things like https://github.com/notion-enhancer/desktop/issues/333 and https://github.com/notion-enhancer/desktop/issues/584, which mean it's possible for there to end up being multiple/hidden windows with a number of memory leaks in each one.

debugging it specifically has been difficult in the past and isn't worth worrying about anymore @lihuelworks, as v0.11.0 has been rewritten from scratch with a number of optimisations and changed behaviours to avoid this happening again. it's just a matter of waiting for release - it might be out sometime around late december or january.
