### ISSUE TITLE
[Win11] App won't automatically open

### ISSUE THREAD

**Issue by heyfrancisco** [notion-enhancer/notion-repackaged#62]
Hi!

_(Sorry if the title may sound misleading, but I will explain the issue. Beware, English isn't my native language, so I will do my best.)_

After installing Notion Repackaged via the .exe file, every time I try to run "Notion Enhanced" from the windows menu or desktop icon, all I get is the **app running in background**.

I have to manually go to my bottom right corner and double-click the icon in the taskbar icon tray. 

I would like to know if there's a fix for this situation, since it's a bummer having to do multiple actions just to open the app.

Thanks in advance!

**Comment by dragonwocky** [comment]
you can disable the "close window to the tray" option or you can use the hotkey (`ctrl+shift+a` by default) to toggle app visibility quickly/in one step
