### ISSUE TITLE
Expand button not working

### ISSUE THREAD

**Issue by T-MC4** [notion-enhancer/notion-repackaged#66]
The app opens up mazimized. All attempts to get Notion Enhanced into windowed mode fail. I've tried uninstalling and using keyboard shortcuts instead of the button. Still won't exit out of maximize.

**Comment by jamezrin** [comment]
What is your OS? If Linux, are you using a WM or a DE?

**Comment by dragonwocky** [comment]
@T-MC4 it sounds to me like you've enabled the "open maximised" option in the menu....
