### ISSUE TITLE
where are the extra options?

### ISSUE THREAD

**Issue by aliafshany** [notion-enhancer/notion-repackaged#68]
hi there
i just isntalled this version of notion and literally there is no difference between original notion and this one.

Is there a Notion enhancer document, FAQ, or guide?
for example i need to change the fonts but there is no options for that
best

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/146498578-d131876c-aea1-4806-9966-913827754304.png)
as there are a variety of themes and extensions you have to enable them before you will see any changes. if you right-click on this icon (in the system tray/menubar), you should be able to open the menu.

the documentation for the current release can be found here: https://github.com/notion-enhancer/desktop/tree/master#readme

most of that will no longer apply after v0.11.0 so new documentation is work in progress.

**Comment by aliafshany** [comment]
i appreciate your response

thank you for this hard work
