### ISSUE TITLE
Headings are the same 

### ISSUE THREAD

**Issue by Pots4342** [notion-enhancer/notion-repackaged#71]
When I opened notion enhanced, the heading regardless of if it's 1, 2, 3, are all the same size

[
![image_2021-12-23_174313](https://user-images.githubusercontent.com/92025159/147221458-8fb75310-5ec1-4e54-a410-02fdf6ef6251.png)
](url)

**Comment by dragonwocky** [comment]
see https://github.com/notion-enhancer/desktop/issues/668
