### ISSUE TITLE
Cannot start the Application

### ISSUE THREAD

**Issue by LePliex** [notion-enhancer/notion-repackaged#75]
System: Arch Linux (KDE)
The Error message is:

(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
14:03:18.161 › Checking for update
Gtk-Message: 14:03:18.485: Failed to load module "appmenu-gtk-module"
(node:12486) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
14:03:18.555 › {
  level: 'info',
  from: 'AssetCache',
  type: 'latestVersionPath',
  data: {
    message: 'latestVersion.json path /home/lepliex/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
14:03:18.558 › Error: Error: ENOENT: no such file or directory, open '/opt/Notion Enhanced/resources/app-update.yml'
14:03:18.559 › {
  level: 'info',
  from: 'AssetCache',
  type: 'errorReadingPath',
  error: {
    name: 'Error',
    message: "ENOENT: no such file or directory, open '/home/lepliex/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'",
    stack: "Error: ENOENT: no such file or directory, open '/home/lepliex/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'"
  },
  data: {
    message: 'Error reading /home/lepliex/.config/notion-app-enhanced/notionAssetCache-v2/latestVersion.json'
  }
}
14:03:18.560 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentVersionLoaded',
  data: {}
}
14:03:18.561 › {
  level: 'info',
  from: 'AssetCache',
  type: 'syncVersionEmptyLatestVersion'
}
14:03:18.561 › {
  level: 'info',
  from: 'AssetCache',
  type: 'currentSyncedAssetsJson',
  data: {}
}
14:03:18.575 › {
  level: 'error',
  from: 'main',
  type: 'unhandledRejection',
  error: {
    name: 'TypeError',
    message: 'focused_window.isMaximized is not a function',
    stack: 'TypeError: focused_window.isMaximized is not a function\n' +
      '    at Object.__exports.createWindow (/opt/Notion Enhanced/resources/app/embedded_enhancer/mods/core/createWindow.js:42:43)\n' +
      '    at handleActivate (/opt/Notion Enhanced/resources/app/main/main.js:71:36)\n' +
      '    at startup (/opt/Notion Enhanced/resources/app/main/main.js:149:5)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  }
}
14:03:18.737 › Websocket listening on 40023...
14:03:18.740 › Set up server listeners with auth (6912c2e61c19cd2d84152d554696e9146d5676cf)...
(node:12486) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
(node:12486) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
14:03:19.945 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.949 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.955 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.955 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.956 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.960 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}
14:03:19.962 › {
  level: 'error',
  from: 'main',
  type: 'uncaughtException',
  error: {
    name: 'TypeError',
    message: 'One-time callback was called more than once',
    stack: 'TypeError: One-time callback was called more than once\n' +
      '    at ClientRequest.<anonymous> (/opt/Notion Enhanced/resources/app/main/schemeHandler.js:194:9)\n' +
      '    at ClientRequest.emit (events.js:315:20)\n' +
      '    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6293)\n' +
      '    at SimpleURLLoaderWrapper.emit (events.js:315:20)'
  }
}

**Comment by pradyungn** [comment]
I'm still having this issue, even after installing the 2.0.18-1 AppImage from the releases tap. Not sure what to do. I haven't been able to use notion locally for a while.
