### ISSUE TITLE
Headings not working

### ISSUE THREAD

**Issue by scanevaro** [notion-enhancer/notion-repackaged#76]
Whenever I try to use headings, 1 2 or 3, it only makes the text bold, it doesn't make the text bigger or anything.

System: Pop OS! latest
Notion Enhanced, only changed font and disabling it didn't make the trick.

What other information can I share? 
Thanks in advance.

**Comment by vasileioskorompilias** [comment]
I face the same issue here as well. With enabled and with disabled the: 1. Font chooser, 2. Any theme.
My OCD instincts kick in :P

Cheers!

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/desktop/issues/668
