### ISSUE TITLE
Bug after latest update [FIXED]

### ISSUE THREAD

**Issue by s0meone247** [notion-enhancer/notion-repackaged#82]
**After The latest update, notion repackaged looks like notion desktop and the tray icon is gone, and alt/option + e doesn't work**

**The application should be working like notion enhanced with a nord theme and apple emojis**

**Screenshot:
![image](https://user-images.githubusercontent.com/72275496/147835983-ac866611-7c01-4462-9551-46110740e321.png)
**

**OS Version: Windows 21H2, Windows 10**

**Notion Repackaged Version: 2.0.18-1, Latest**

**Extensions & Theme: Focus Mode, Nord Theme, Apple Emojis, Calendar Scroll.**

**Comment by jamezrin** [comment]
Between 2.0.16-5 and 2.0.18-1 you have to delete your local notion-enhancer data.
To do that, just go to your home directory and delete the `.notion-enhancer` directory, after that your settings should reset and notion-enhancer should appear in the sidebar.

**Comment by milan-tom** [comment]
Thank you! This fixed my issue (I was having the same problem). Is this mentioned in the documentation? I didn't see it.

**Comment by s0meone247** [comment]
> Between 2.0.16-5 and 2.0.18-1 you have to delete your local notion-enhancer data. To do that, just go to your home directory and delete the `.notion-enhancer` directory, after that your settings should reset and notion-enhancer should appear in the sidebar.

The problem still occurs

**Comment by milan-tom** [comment]
> > Between 2.0.16-5 and 2.0.18-1 you have to delete your local notion-enhancer data. To do that, just go to your home directory and delete the `.notion-enhancer` directory, after that your settings should reset and notion-enhancer should appear in the sidebar.
> 
> The problem still occurs

I had to uninstall `2.0.18-1`, clear the data, and then reinstall it for it to work. Perhaps this will work for you.

**Comment by jamezrin** [comment]
> Thank you! This fixed my issue (I was having the same problem). Is this mentioned in the documentation? I didn't see it.

Yeah, I think you are right, there is no mention of this in the docs, we will probably add it soon.



> > Between 2.0.16-5 and 2.0.18-1 you have to delete your local notion-enhancer data. To do that, just go to your home directory and delete the `.notion-enhancer` directory, after that your settings should reset and notion-enhancer should appear in the sidebar.
> 
> The problem still occurs [edit] I didn't realize that this versionwas different. it works fine. thanks

Perfect, I am going to keep this issue open for a while, just for people that might have this same issue.

**Comment by dragonwocky** [comment]
@jamezrin @milan-tom it is in the documentation, at the top of the installation instructions
