### ISSUE TITLE
Notion Repackaged Still Lunching as Normal Notion Even after trying the fix

### ISSUE THREAD

**Issue by kayloremetre** [notion-enhancer/notion-repackaged#83]
**What is happening?**
Notion Repackaged is Still Lunching as Normal Notion even after deleting .notionenhancer

**What should be happening?**

**Screenshots (if applicable):**
Here's the console, as advised
![image](https://user-images.githubusercontent.com/56988117/147842243-74793ded-391b-4d1c-8f90-f70ce021639d.png)

**Operating system/browser name & version:**
Windows 11
**notion-enhancer and/or notion-repackaged version:**
notion enhancer v0.11.0, notion repackaged 2.0.18-1
**notion-enhancer configuration (enabled/disabled mods and their settings):**
none

**Comment by dragonwocky** [comment]
please scroll up and show the top of the console and also provide a screenshot of the notion app

**Comment by kayloremetre** [comment]
ohhh nvm i thought the settings didnt move, it did work I'm so sorry ;-;
