### ISSUE TITLE
Extract: Error writing to file Uninstall Notion Enhanced.exe | Windows

### ISSUE THREAD

**Issue by Nek-12** [notion-enhancer/notion-repackaged#84]
**What is happening?**  
The installation script throws an error and shuts down, leaving the installation incomplete.
`Extract: Error writing to file Uninstall Notion Enhanced.exe`  
Checking the installation directory during / after the installation reveals that no such file is present in the folder.

**What should be happening?**
Notion installs successfully

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/46318640/147870946-bacd7a38-a0e2-476f-96c6-bd58c7137f06.png)

**Operating system/browser name & version:**
Edition	Windows 11 Home
Version	21H2
Installed on	‎11-‎Sep-‎21
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0
System type	64-bit operating system, x64-based processor

**notion-enhancer and/or notion-repackaged version:**
2.0.18-1 Setup
**notion-enhancer configuration (enabled/disabled mods and their settings):**
N/A

**Comment by dragonwocky** [comment]
I'm on the same build Windows, installing the same .exe, and it's working fine. Nobody else has reported this problem- is it possible that there are some file conflicts (e.g. the previous version of the app not being properly removed first) or some permissions problems on your side?

**Comment by Nek-12** [comment]
The issue was caused by lack of storage space on target drive.
You may decide to #wontfix this issue or add a proper message and/or free space check to the installer

**Comment by dragonwocky** [comment]
I don't think this is something controlled by the notion-enhancer, our installer is created by https://github.com/electron-userland/electron-builder - it may be better to open a bug report there? @jamezrin will know better than me, though.

**Comment by jamezrin** [comment]
I have seen another issue in electron-builder which was dismissed for the same reason, lack of storage space, so yeah there is not much to do.
