### ISSUE TITLE
Tray icon missing and notion enhancer features not working

### ISSUE THREAD

**Issue by ocean-orrick** [notion-enhancer/notion-repackaged#86]
**What is happening?**
After updating, notion repackaged tray icon is missing and no notion enhancer features seem to be working

**What should be happening?**
Tray icon should be visible to enable various notion enhancer features

**Operating system/browser name & version:**
Windows 10

**notion-enhancer and/or notion-repackaged version:**
notion repackaged 2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**
N/A

**Comment by Whale-fall** [comment]
Same problem in window11 build 22523
![image](https://user-images.githubusercontent.com/22662209/148005397-0d558963-e823-43e1-8cb0-e1fd423f4e99.png)

**Comment by MortyFx** [comment]
Same probem on macOS.
Notion Enhanced version: 2.0.18-1

**Comment by SkysCrystal** [comment]
The same problem on windows 10. No tray icon. And `Ctrl+Shift+A` or `Ctrl+Shift+E` won't work.
Enhancer version: 2.0.18-1
Notion : 2.14.23.10.16.12

**Comment by inspirepan** [comment]
Same problem on macOS monterey
version: 2.0.18-1

**Comment by sidevesh** [comment]
Same here on Windows 11, can't even downgrade since the app triggers install of update on launch post downgrade

**Comment by Kourai** [comment]
Same here on Ubuntu 20.04.3 LTS

BUT, as I was trying to check my notion-enhancer version, I tried to launch it via CLI `notion-app-enhanced --help` 
which didn't show any man page, but re-open the notion app, and now I can see the `notion-enhancer` menu entry, and modify my settings. It seems to work fine !

**Comment by Ocanamat** [comment]
I had the same bug, and after deleting my `.notion-enhancer` folder in my user folder (win10) the program launched with a notion-enhancer menu under my top links in the side bar. 

![image](https://user-images.githubusercontent.com/13169121/148068711-a1e2face-1aab-4078-a9c2-5a1ee1612e5a.png)

Just delete the folder as specified in [https://notion-enhancer.github.io/getting-started/installation/](https://notion-enhancer.github.io/getting-started/installation/)

Cheers,

**Comment by ocean-orrick** [comment]
@Ocanamat thanks, that fixed it for me!

**Comment by SkysCrystal** [comment]
@Ocanamat Thanks!!!

**Comment by spencershastings** [comment]
@Ocanamat What should I do if that didn't work for me?

**Comment by Ocanamat** [comment]
> @Ocanamat What should I do if that didn't work for me?

Buah, really don't know ¯\_(ツ)_/¯. But If it hadn't worked for me, this is what I would've tried:

1. Install and uninstall the old npm notion-enhancer module, mainly because I know it is still around in my system and it could be causing trouble. I did not know how it fully injected itself, but I messed with some of the .css files and by reinstalling from there I got some things repaired.
2. Install an old `notion-repackaged` version (check it works with the old menu), delete the folder, then upgrade. You can download the old releases from [https://github.com/notion-enhancer/notion-repackaged/releases](https://github.com/notion-enhancer/notion-repackaged/releases).
3. Seek everything Notion related with Everything search, and nuke it... trying to start with the cleanest slate possible.

Hope you get it working for you 🙃

**Comment by spencershastings** [comment]
@Ocanamat not to be that person, but I've nuked everything related to notion and enhancer I'm pretty sure, and nothing is still showing up. thank you anyway! sorry for troubling you. hopefully I'll figure something out.

**Comment by spencershastings** [comment]
@Ocanamat yeah just to confirm, the old version works, but the new one doesn't for some reason. even after nuking absolutely everything from the old version.

**Comment by Moyf** [comment]
> I had the same bug, and after deleting my `.notion-enhancer` folder in my user folder (win10) the program launched with a notion-enhancer menu under my top links in the side bar.
> 
> ![image](https://user-images.githubusercontent.com/13169121/148068711-a1e2face-1aab-4078-a9c2-5a1ee1612e5a.png)
> 
> Just delete the folder as specified in https://notion-enhancer.github.io/getting-started/installation/
> 
> Cheers,

Thanks, That's how I solved the problem!

**Comment by Hariienesh1901** [comment]
I also had the same error.

But I figured it out it was here.

![image](https://user-images.githubusercontent.com/76608849/148500951-4904159a-8f8f-4d7f-87a7-b6ceb56d037c.png)

In your sidebar after Settings & Member

**Comment by dragonwocky** [comment]
This is not a bug. This is expected. Following the installation instructions fully & correctly (including the **warning** at the very top) will solve this.
![image](https://user-images.githubusercontent.com/16874139/148630287-37f73efd-4dd0-43d9-808b-655ec10c5f46.png)
