### ISSUE TITLE
App don't start on linux

### ISSUE THREAD

**Issue by GP-S** [notion-enhancer/notion-repackaged#89]
**What is happening?**
On  Archlinux :  notion-app 2.0.16-14 window starts, but keeps continuously loading and never opens completely.

Cleaning profile ( rm ~/.config/notion-app/)and reinstallation failed to fix the issue.

The only error I got form console refer to the missing file :  /opt/notion-app/resources/app-update.yml

Looking at localhost:43359 got the message : Upgrade Required

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/9041351/148591895-cde60d8e-9f3c-43e6-8e74-6b8c698a870e.png)

**Operating system/browser name & version:**

OS: Arch Linux x86_64 
Kernel: 5.15.13-arch1-1
DE: GNOME 41.2 

**notion-enhancer and/or notion-repackaged version:**
notion-app 2.0.16-14

**notion-enhancer configuration (enabled/disabled mods and their settings):**
NA

**Comment by GP-S** [comment]
The app has been installed from the AUR package maintened by @jamezrin

**Comment by jamezrin** [comment]
Expected. Install latest release (2.0.18-1)
