### ISSUE TITLE
Mod bug - Outliner 

### ISSUE THREAD

**Issue by CJHS5** [notion-enhancer/notion-repackaged#90]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

**What is happening?**
if there are too many headings, which will make the headings in the outliner out of the box.
**What should be happening?**
maybe a scroll bar  for otuliner
**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/71076192/150523996-450ebdc9-3d56-4cb7-b901-de6ccd25947a.png)

**Operating system/browser name & version:**
Windows/ 
**notion-enhancer and/or notion-repackaged version:**
notion-repackaged version
**notion-enhancer configuration (enabled/disabled mods and their settings):**
mods enabled/ outliner

**Comment by dragonwocky** [comment]
https://github.com/notion-enhancer/notion-enhancer/issues/881
