### ISSUE TITLE
Enhancements menu disappeared in MacOS?

### ISSUE THREAD

**Issue by Ngort** [notion-enhancer/notion-repackaged#91]
**What is happening?**
Notion Repackaged: No way to access Enhancements Menu and apply mods / enhancements after updating to 2.0.18-1 by replacing folder in Applications.

**What should be happening?**
I should be able to access such menu with Cmd+E or Option+E or some similar hotkey, and there should be a Notion icon on my taskbar.

**Screenshots (if applicable):**
N/A

**Operating system/browser name & version:**
MacOS Monterrey 12.0.1, M1Max Macbook Pro

**notion-enhancer and/or notion-repackaged version:**

2.0.18-1 Intel dmg

**notion-enhancer configuration (enabled/disabled mods and their settings):**
N/A? Can't see.

**Comment by dragonwocky** [comment]
exact same as https://github.com/notion-enhancer/desktop/issues/721, please do not open duplicate issues
