### ISSUE TITLE
Themes Damaged

### ISSUE THREAD

**Issue by true-Grand** [notion-enhancer/notion-repackaged#92]
**Theme is only applying for the bottom half of Notion.**

**Themes should be applied on everything.**

**Screenshots**
<img width="840" alt="Screen Shot 2022-01-25 at 8 47 01 AM" src="https://user-images.githubusercontent.com/78011648/150889697-369821d8-b244-4a93-92de-d906d06b401b.png">

**macOS Notion Repackaged, Version 2.0.18-1**

**notion-enhancer and/or notion-repackaged version:**

**Core + Themes**

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/892
