### ISSUE TITLE
Tabs mod hotkeys does not work on mac

### ISSUE THREAD

**Issue by edofe99** [notion-enhancer/notion-repackaged#94]
**What is happening?**
In macos pre-packaged app there's a bug that does not make tabs mod hotkeys work, if I configure it to cmd+T it read the key as "meta" and it does not work:
![image](https://user-images.githubusercontent.com/62611612/152843262-ca5058ce-97e3-4609-bcc6-91e3dd31d0b6.png)

**What should be happening?**
When pressing cmd+t when assigning a short cut it should diplay cmd+t instead of "meta"+t... and also it should work. 
**Screenshots (if applicable):**
**Operating system/browser name & version:**
I'm on macos monterey updated to last version. 
**notion-enhancer and/or notion-repackaged version:**
I'm on the last version, downloaded a couple of hours ago directly from gut-hub page.
**notion-enhancer configuration (enabled/disabled mods and their settings):**
The only mod enabled is Tabs. 

**_Extra:_**
There's a problem that makes tabs to be displayed below window buttons:
![image](https://user-images.githubusercontent.com/62611612/152843750-99b3d4cb-6890-4baa-861c-01ec9e898070.png)

**Comment by dragonwocky** [comment]
dup of https://github.com/notion-enhancer/notion-enhancer/issues/880
note that meta is the correct key, it is equivalent to cmd on macOS or win on Windows
