### ISSUE TITLE
Error:  notion installation has been corrupted, no executable found.

### ISSUE THREAD

**Issue by zdxsector** [notion-enhancer/notion-repackaged#95]
**What is happening?**
Error to apply notion enhancer in linux 
 ```bash 
 Error:  notion installation has been corrupted, no executable found.
at default (file:///home/sly/node-v14.18.0-linux-x64/lib/node_modules/notion-enhancer/pkg/apply.mjs:27:13)
  at file:///home/sly/node-v14.18.0-linux-x64/lib/node_modules/notion-enhancer/bin.mjs:105:25
  at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
  at async Loader.import (internal/modules/esm/loader.js:178:24)
  at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Operating system/browser name & version:**
Linux 5.16.0-1-amd64

**notion-enhancer and/or notion-repackaged version:**
[(notion-enhancer v0.11.0)](https://github.com/notion-enhancer/notion-repackaged/commit/4eefa99dc1bcde18268d70bb2b7f050786229feb)

**Comment by dragonwocky** [comment]
to run `notion-enhancer apply` you need an official build of Notion to be pre-installed, which you can't have on Linux.

try actually following the installation instructions this time (the installation should include both Notion and the notion-enhancer builtin): https://notion-enhancer.github.io/getting-started/installation

**Comment by zdxsector** [comment]
I can't install both vanilla and enhanced how could I install both of them?

**Comment by dragonwocky** [comment]
@slyg3nius you shouldn't. If you need one to be vanilla and the other to be enhanced, use one as an app and the other in your browser.

**Comment by zdxsector** [comment]
so there is no way I can use the enhancer apply? because after installing notion-app-enhancer in my machine I could not see for enhancer.

**Comment by zdxsector** [comment]
Wait.. now it works. What I did is I run the notion-repackaged.sh then afterwards I reinstall the notion-app-enhancer.
![image](https://user-images.githubusercontent.com/64179667/153748159-b8ba201d-40a5-4e45-96d9-8a637da01649.png)


You should include this to the installation instruction because it is quite confusing for linux users.

**Comment by dragonwocky** [comment]
> Wait.. now it works. What I did is I run the notion-repackaged.sh then afterwards I reinstall the notion-app-enhancer.

You don't need to do that...

This is all you should be doing.
```
echo "deb [trusted=yes] https://apt.fury.io/notion-repackaged/ /" | sudo tee /etc/apt/sources.list.d/notion-repackaged.list
sudo apt update
sudo apt install notion-app-enhanced
```

> so there is no way I can use the enhancer apply?

The installation instructions very specifically say you can't. Please read them carefully. They are correct, as long as you don't make things up to add to them.

**Comment by zdxsector** [comment]
No that doesn't work at first I tried that then I install the notion-app-enhanced but there is no enhancer in the Application. I do reinstalling 10 times but nothing to see the enhancer menu that's why I tried runing the executable command of notion-repackaged.

**Comment by dragonwocky** [comment]
@slyg3nius did you delete the folder you were told to by the very top of the instructions? If you don't delete it then the menu doesn't show up in the sidebar.

Running the script may have deleted it for you, but you really shouldn't be running that script.

![image](https://user-images.githubusercontent.com/16874139/153748796-97ff7c13-8463-402b-9a8c-cb1213b24f66.png)

**Comment by zdxsector** [comment]
I did delete the folder while reinstalling so many times.

**Comment by dragonwocky** [comment]
Was the folder called `notion-enhancer`, or `.notion-enhancer`? The `.` is important. If you delete the one without the dot then you're deleting the actual notion-enhancer and it's no surprise if things aren't working.

If you did delete the one with the dot, then that's probably why the app started working.

The script you ran builds the sources for the app - it doesn't create or affect any actual app installations on your system.

**Comment by zdxsector** [comment]
.notion-enchancer with dot(.)

**Comment by zdxsector** [comment]
will also create new issue the themes in enhancer doesn't work at all.

**Comment by dragonwocky** [comment]
@slyg3nius dark themes will only work if you put Notion into dark mode first (within your Notion settings), this isn't a bug.

**Comment by zdxsector** [comment]
so why it doesn't work for many times while deleting also .notion-enhanced folder?

**Comment by dragonwocky** [comment]
I'm very confused as to what you're doing. Once you've installed notion-enhancer and gotten into the menu you don't need to keep deleting it - it's used to store the notion-enhancer's settings, delete it will reset the settings. You only need to delete it once at the start to get rid of the old format from notion-enhancer v0.10.
