### ISSUE TITLE
Can't access any notion enhancer settings in repackaged app on Linux Mint

### ISSUE THREAD

**Issue by quietmansoath** [notion-enhancer/notion-repackaged#96]
BEFORE MAKING A BUG REPORT, PLEASE READ THE
[CONTRIBUTING](https://notion-enhancer.github.io/about/contributing) GUIDE.

BUG REPORTS ARE NOT FOR SUPPORT REQUESTS. IF YOU JUST NEED HELP,
ASK IN THE [DISCORD](https://discord.gg/sFWPXtA) SERVER.

BUG REPORTS THAT DO NOT PROPERLY FILL
IN THE TEMPLATE MAY BE IGNORED OR REJECTED.
YOU MUST DELETE ALL TEXT ON OR ABOVE THIS LINE BEFORE SUBMITTING.

What is happening?

When I launch Notion (using repackaged version on desktop), no icon shows up for the enhancer, neither in the tray nor within the app. In other words, I have no means of getting to the "enhancer" features.

What should be happening?

I expect to be able to see the option for notion enhancer in the first screenshot on this page: https://notion-enhancer.github.io/getting-started/basic-usage/ and also see the enhancer icon in my system tray and I do not.

Screenshots (if applicable):

Operating system/browser name & version:

Linux Mint 20.2 Cinnamon

notion-enhancer and/or notion-repackaged version:

Notion 2.0.18-1 (notion-enhancer 0.11.0) (repackaged version)

notion-enhancer configuration (enabled/disabled mods and their settings):

Unfortunately I don't remember--a custom font was used, I know, but I had turned that off. I think this issue has been here for awhile but the last time I felt the need to use the enhancer features was in December, so I'm not sure when I noticed everything disappeared.

That said I did fully remove and reinstall notion-app-enhanced today and am having the same issue.

**Comment by blkksheepp** [comment]
same issue

**Comment by dragonwocky** [comment]
@quietmansoath @Random-Pickle this is expected if you're updating from a previous version of the notion-enhancer (which you must be, if the last time you used it was in December) and you haven't followed the installation instructions properly.

![](https://user-images.githubusercontent.com/16874139/148630287-37f73efd-4dd0-43d9-808b-655ec10c5f46.png)

Deleting the `~/.notion-enhancer` folder and re-launching and/or re-installing the app should fix this.

**Comment by quietmansoath** [comment]
Thanks, this was helpful. However, the location of these instructions on the webpage it was screenshot from is confusing. Being as you guys have two different githubs for notion-repackaged and regular, unbundled enhancer, the instructions seemed like they apply to only the latter and not the former, so I ignored them.
