### ISSUE TITLE
Add Pacstall installation option for Debian/Ubuntu users

### ISSUE THREAD

**Issue by IOplus** [notion-enhancer/notion-repackaged#98]
[Pacstall](https://github.com/pacstall/pacstall) is a community-driven AUR-like package manager for Ubuntu. We have added [notion-app](https://github.com/pacstall/pacstall-programs/pull/1118) and have an ongoing pull request to add [notion-app-enhanced](https://github.com/pacstall/pacstall-programs/pull/1122) to our repository.

We have a few questions for you:
* Would you like to maintain the pacscripts (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.
* Could you include a section in your documentation showing Pacstall as a valid method of installation for notion-app and notion-app-enhanced for Debian/Ubuntu users? We could make a pull request for that if you want.

**Comment by dragonwocky** [comment]
Pacstall looks great, thanks for letting us know.

> Would you like to maintain the pacscripts (similar to a PKGBUILD) yourself? We can maintain it for you if you decide not to.

I'll leave that to @jamezrin to decide.

As far as I can tell, all we would need to do would be to [bump the version numbers](https://github.com/pacstall/pacstall-programs/blob/f5a339a1506f26d2c592781b9c0147bca19f8fe6/packages/notion-app-enhanced-deb/notion-app-enhanced-deb.pacscript#L4) in the pacscripts on update, right? If so, it may be handy to be able to do it ourselves so we can try and release to as many platforms as possible simultaneously.

@IOplus if we were to self-maintain the pacscipts, would that best be done by creating our own repository users add to their registries with `pacstall -A`, or by updating the files in the default repository?

> Could you include a section in your documentation showing Pacstall as a valid method of installation for notion-app and notion-app-enhanced for Debian/Ubuntu users? We could make a pull request for that if you want.

Sure. It looks like the installation would just be to replace `sudo apt i` with `pacstall -I`? I can add that to the website once we're ready to go.

**Comment by Elsie19** [comment]
> As far as I can tell, all we would need to do would be to [bump the version numbers](https://github.com/pacstall/pacstall-programs/blob/f5a339a1506f26d2c592781b9c0147bca19f8fe6/packages/notion-app-enhanced-deb/notion-app-enhanced-deb.pacscript#L4) in the pacscripts on update, right?

Yes, along with the shasum.

> @IOplus if we were to self-maintain the pacscipts, would that best be done by creating our own repository users add to their registries with pacstall -A, or by updating the files in the default repository?

You should keep pacscripts in the main, official repository, as that will give users the easiest method of finding/installing notion (as it is the preinstalled repo on every Pacstall installation). If you opt to make your own repo, your users would first have to run `pacstall -A https://notion-enhancer/pacscript-repo`, or something of that nature, *then* run `pacstall -I notion-app-enhancer-deb`, whereas if it's in the official repo, they just have to run the last command.

---

Hope that clears up any confusion!

**Comment by jamezrin** [comment]
> > As far as I can tell, all we would need to do would be to [bump the version numbers](https://github.com/pacstall/pacstall-programs/blob/f5a339a1506f26d2c592781b9c0147bca19f8fe6/packages/notion-app-enhanced-deb/notion-app-enhanced-deb.pacscript#L4) in the pacscripts on update, right?
> 
> Yes, along with the shasum.
> 
> > @IOplus if we were to self-maintain the pacscipts, would that best be done by creating our own repository users add to their registries with pacstall -A, or by updating the files in the default repository?
> 
> You should keep pacscripts in the main, official repository, as that will give users the easiest method of finding/installing notion (as it is the preinstalled repo on every Pacstall installation). If you opt to make your own repo, your users would first have to run `pacstall -A https://notion-enhancer/pacscript-repo`, or something of that nature, _then_ run `pacstall -I notion-app-enhancer-deb`, whereas if it's in the official repo, they just have to run the last command.
> 
> Hope that clears up any confusion!

Pacstall looks great, but I think maintaining our own repository makes installing our packages through Pacstall a lot less appealing. 

After all, a lot of the interest in AUR comes from people using AUR helpers that make it super easy to install packages, without having to build the package themselves or going back to the APT, RPM way of dealing with packages with repos.

I assume that for us, updating the packages would mean submitting a PR to the main repo on each version change, right? I would in that case prefer if you maintained the packages.

**Comment by brianrobt** [comment]
> Pacstall looks great, but I think maintaining our own repository makes installing our packages through Pacstall a lot less appealing.

Perhaps work can be done with the Pacstall team to come up with a solution for this problem.

> I assume that for us, updating the packages would mean submitting a PR to the main repo on each version change, right? I would in that case prefer if you maintained the packages.

That's a great follow-up question to the problem you stated.

**Comment by Elsie19** [comment]
Well, it seems that notion is in [repology](https://repology.org/project/notion-app-enhanced/versions), which means that you can use [PacUp](https://github.com/pacstall/pacup) to easily update the version and hash, then push to a branch where you can easily make a PR. It will take care of everything except the actual PR making.


Example:

Make sure this is run inside a git repo, preferably a fork of the Pacstall one.
```bash
# outdated pacscript
name="notion-app-deb"
pkgname="notion-app"
repology=("project: ${pkgname}")
version="2.0.16-6"
url="https://github.com/notion-enhancer/notion-repackaged/releases/download/v${version}/${pkgname}_${version}_amd64.deb"
breaks="${pkgname}-app ${pkgname}-enhanced-deb ${pkgname}-enhanced-app"
replace="${pkgname}"
gives="${pkgname}"
description="The all-in-one workspace for your notes and tasks"
hash="233a54f7d5db26eb556f66aac8eba24e45af3714098885ba6cc322e6fd454bb3"
```

Install Pacup, then run `pacup -r notion-app-deb.pacscript`. It will update the hash and version, then commit and push.

**Comment by jamezrin** [comment]
Hey, just remembered about this issue.
On future releases, we can take care of the pacscript update and PR creation via a CI/CD workflow, similar to what we do for the gemfury repo. I will probably setup something similar for the AUR.
